spring.application.name=Qatu

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/qatu_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

server.port=6060

qatu.heatmap.umbral-rojo=10
qatu.heatmap.umbral-amarillo=5
qatu.heatmap.radio-metros=100
qatu.firebase.credentials-path=qatu-app-firebase-adminsdk-fbsvc-8e06dd4949.json